# Generated by Django 5.2.8 on 2025-11-18 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('role', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Staffmanagement',
            fields=[
                ('manage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.person')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staffmanagement_staff_set', to='users.person')),
            ],
            options={
                'db_table': 'staffmanagement',
            },
        ),
        migrations.CreateModel(
            name='Staffprofile',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.person')),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.salary')),
            ],
            options={
                'db_table': 'staffprofile',
            },
        ),
    ]
