# Generated by Django 5.2.8 on 2025-11-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Staffprofile',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.person')),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.salary')),
            ],
            options={
                'db_table': 'staffprofile',
            },
        ),
        migrations.CreateModel(
            name='Staffmanagement',
            fields=[
                ('manage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.person')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.staffprofile')),
            ],
            options={
                'db_table': 'staffmanagement',
            },
        ),
    ]
