# Generated by Django 5.2.8 on 2025-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'fund',
            },
        ),
        migrations.CreateModel(
            name='Fundtransaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fundtransaction',
            },
        ),
    ]
