# Generated by Django 5.2.8 on 2025-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=100)),
                ('fund_amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'fund',
            },
        ),
        migrations.CreateModel(
            name='Fundtransaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('old_fund', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_fund', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'fundtransaction',
            },
        ),
    ]
