# Generated by Django 5.2.8 on 2025-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary_rank', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('multiplier', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Salarychangehistory',
            fields=[
                ('history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('old_multiplier', models.FloatField(blank=True, null=True)),
                ('new_multiplier', models.FloatField(blank=True, null=True)),
                ('change_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'salarychangehistory',
            },
        ),
        migrations.CreateModel(
            name='Salarypayment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'salarypayment',
            },
        ),
    ]
