# Generated by Django 5.2.8 on 2025-11-18 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarychangehistory',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salarychangehistory_admin_set', to='users.person'),
        ),
        migrations.AddField(
            model_name='salarychangehistory',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.salary'),
        ),
        migrations.AddField(
            model_name='salarychangehistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.person'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salarypayment_admin_set', to='users.person'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.salary'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.person'),
        ),
    ]
