# Generated by Django 5.2.8 on 2025-11-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.IntegerField(primary_key=True, serialize=False)),
                ('leave_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='Leavedetail',
            fields=[
                ('detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.leave')),
            ],
            options={
                'db_table': 'leavedetail',
            },
        ),
    ]
